# Generated by Django 3.2.10 on 2021-12-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='ani/ani/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '캐릭터',
                'verbose_name_plural': '캐릭터 이름들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani.ani')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='ani',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani.category'),
        ),
        migrations.AddField(
            model_name='ani',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='ani.Tag'),
        ),
    ]
