# Generated by Django 3.2.9 on 2021-11-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('gender', models.CharField(choices=[('남', '남'), ('여', '여')], default='', max_length=2, verbose_name='성별')),
                ('pub_date', models.DateField(verbose_name='생일')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('mobile', models.CharField(max_length=13, verbose_name='연락처')),
            ],
        ),
    ]
