# Generated by Django 3.2.9 on 2021-12-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirby',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='star.category'),
            preserve_default=False,
        ),
    ]
