# Generated by Django 3.2.9 on 2021-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
