# Generated by Django 3.2.9 on 2021-11-30 08:40

from django.db import migrations, models
import haeund.upload_to


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to=haeund.upload_to.uuid_name_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
